services:
  - type: web
    name: smm-panel
    env: docker
    repo: https://github.com/bytepassperks/smm-panel.git
    region: oregon

databases:
  - name: smm-panel-db
    type: mysql
    plan: free
    region: oregon